#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1554930771.934739
__CHEETAH_genTimestamp__ = 'Wed Apr 10 14:12:51 2019'
__CHEETAH_src__ = 'MdCmdTablePage.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Apr 10 11:25:47 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class MdCmdTablePage(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(MdCmdTablePage, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<title>''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 1, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 1, col 8.
        write(u''' Component Dictionary</title>
## ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 2, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 2, col 6.
        write(u''' Component Dictionary

''')
        if VFSL([locals()]+SL+[globals(), builtin],"has_commands",True): # generated from line 4, col 1
            write(u'''
###Command: ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 6, col 16
            if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 6, col 16.
            write(u'''

|Mnemonic|ID|Description|Arg Name|Arg Type|Comment
|---|---|---|---|---|---|
''')
            for mnemonic, opcode, sync, priority, full, comment in VFSL([locals()]+SL+[globals(), builtin],"commands",True): # generated from line 10, col 1
                args = VFSL([locals()]+SL+[globals(), builtin],"command_args",True)[VFSL([locals()]+SL+[globals(), builtin],"mnemonic",True)]
                args_length = len(VFSL([locals()]+SL+[globals(), builtin],"args",True)) + 1
                if len(VFSL([locals()]+SL+[globals(), builtin],"opcode",True)) == 1: # generated from line 13, col 2
                    opcode = VFSL([locals()]+SL+[globals(), builtin],"opcode",True)[0]
                    if "x" in VFSL([locals()]+SL+[globals(), builtin],"opcode",True): # generated from line 15, col 5
                        opcode = int(VFSL([locals()]+SL+[globals(), builtin],"opcode",True), 16) + VFSL([locals()]+SL+[globals(), builtin],"base_id",True)
                    else: # generated from line 17, col 5
                        opcode = int(VFSL([locals()]+SL+[globals(), builtin],"opcode",True)) + VFSL([locals()]+SL+[globals(), builtin],"base_id",True)
                    hexopcode = hex(VFSL([locals()]+SL+[globals(), builtin],"opcode",True))
                write(u'''|''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"mnemonic",True) # u'${mnemonic}' on line 22, col 2
                if _v is not None: write(_filter(_v, rawExpr=u'${mnemonic}')) # from line 22, col 2.
                write(u'''|''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"opcode",True) # u'${opcode}' on line 22, col 14
                if _v is not None: write(_filter(_v, rawExpr=u'${opcode}')) # from line 22, col 14.
                write(u''' (''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"hexopcode",True) # u'${hexopcode}' on line 22, col 25
                if _v is not None: write(_filter(_v, rawExpr=u'${hexopcode}')) # from line 22, col 25.
                write(u''')|''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"comment",True) # u'${comment}' on line 22, col 39
                if _v is not None: write(_filter(_v, rawExpr=u'${comment}')) # from line 22, col 39.
                write(u'''| | |\t
''')
                if VFSL([locals()]+SL+[globals(), builtin],"args_length",True) > 1: # generated from line 23, col 6
                    args_index = 1
                    for arg_name, arg_type, comment, typeinfo in VFSL([locals()]+SL+[globals(), builtin],"args",True): # generated from line 25, col 7
                        write(u'''| | | |''')
                        _v = VFSL([locals()]+SL+[globals(), builtin],"arg_name",True) # u'$arg_name' on line 26, col 8
                        if _v is not None: write(_filter(_v, rawExpr=u'$arg_name')) # from line 26, col 8.
                        write(u'''|''')
                        _v = VFSL([locals()]+SL+[globals(), builtin],"arg_type",True) # u'$arg_type' on line 26, col 18
                        if _v is not None: write(_filter(_v, rawExpr=u'$arg_type')) # from line 26, col 18.
                        write(u'''|''')
                        _v = VFSL([locals()]+SL+[globals(), builtin],"comment",True) # u'$comment' on line 26, col 28
                        if _v is not None: write(_filter(_v, rawExpr=u'$comment')) # from line 26, col 28.
                        write(u'''|\t\t\t\t\t
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_MdCmdTablePage= 'respond'

## END CLASS DEFINITION

if not hasattr(MdCmdTablePage, '_initCheetahAttributes'):
    templateAPIClass = getattr(MdCmdTablePage, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(MdCmdTablePage)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=MdCmdTablePage()).run()


