#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1554930765.798479
__CHEETAH_genTimestamp__ = 'Wed Apr 10 14:12:45 2019'
__CHEETAH_src__ = 'protectedSerialH.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Apr 10 11:25:47 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class protectedSerialH(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(protectedSerialH, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''protected:

    enum {
        TYPE_ID = ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"uuid",True) # u'${uuid}' on line 4, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'${uuid}')) # from line 4, col 19.
        write(u''' //!< type id
    };

''')
        for (name,type,size,format,comment,typeinfo) in VFSL([locals()]+SL+[globals(), builtin],"members",True): # generated from line 7, col 1
            if VFSL([locals()]+SL+[globals(), builtin],"size",True) == None or typeinfo == 'string': # generated from line 8, col 1
                write(u'''    ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"type",True) # u'${type}' on line 9, col 5
                if _v is not None: write(_filter(_v, rawExpr=u'${type}')) # from line 9, col 5.
                write(u''' m_''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 9, col 15
                if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 9, col 15.
                write(u'''; //<! ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 9, col 29
                if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 9, col 29.
                write(u''' - ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"comment",True) # u'${comment}' on line 9, col 39
                if _v is not None: write(_filter(_v, rawExpr=u'${comment}')) # from line 9, col 39.
                write(u'''
''')
            else: # generated from line 10, col 1
                write(u'''    ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"type",True) # u'${type}' on line 11, col 5
                if _v is not None: write(_filter(_v, rawExpr=u'${type}')) # from line 11, col 5.
                write(u''' m_''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 11, col 15
                if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 11, col 15.
                write(u'''[''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"size",True) # u'${size}' on line 11, col 23
                if _v is not None: write(_filter(_v, rawExpr=u'${size}')) # from line 11, col 23.
                write(u''']; //<! ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 11, col 38
                if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 11, col 38.
                write(u''' - ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"comment",True) # u'${comment}' on line 11, col 48
                if _v is not None: write(_filter(_v, rawExpr=u'${comment}')) # from line 11, col 48.
                write(u'''

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_protectedSerialH= 'respond'

## END CLASS DEFINITION

if not hasattr(protectedSerialH, '_initCheetahAttributes'):
    templateAPIClass = getattr(protectedSerialH, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(protectedSerialH)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=protectedSerialH()).run()


