#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1554930770.190796
__CHEETAH_genTimestamp__ = 'Wed Apr 10 14:12:50 2019'
__CHEETAH_src__ = 'HtmlChannelTablePage.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Apr 10 11:25:47 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class HtmlChannelTablePage(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(HtmlChannelTablePage, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<!DOCTYPE html>
<html>
<head>
<title>''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 4, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 4, col 8.
        write(u''' Component Dictionary</title>
</head>
<body>

<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
}
th {
    text-align: left;
}
html {
    font-family: Arial, sans-serif ;
    font-size: 90% ;
}
</style>


''')
        if VFSL([locals()]+SL+[globals(), builtin],"has_telemetry",True): # generated from line 26, col 1
            write(u'''<h1><b>Telemetry Channels: ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 27, col 28
            if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 27, col 28.
            write(u'''</b></h1>
<table>
  <tr>
     <th>Channel Name</th>
     <th>ID</th>
     <th>Type</th>
     <th>Description</th>
 </tr>

''')
            for id, tlmname, type, size, update, comment, typeinfo in VFSL([locals()]+SL+[globals(), builtin],"channels",True): # generated from line 36, col 1
                # 
                if len(VFSL([locals()]+SL+[globals(), builtin],"id",True)) == 1: # generated from line 38, col 5
                    id = VFSL([locals()]+SL+[globals(), builtin],"id",True)[0]
                    if "x" in VFSL([locals()]+SL+[globals(), builtin],"id",True): # generated from line 40, col 8
                        id = int(VFSL([locals()]+SL+[globals(), builtin],"id",True), 16) + VFSL([locals()]+SL+[globals(), builtin],"base_id",True)
                    else: # generated from line 42, col 8
                        id = int(VFSL([locals()]+SL+[globals(), builtin],"id",True)) + VFSL([locals()]+SL+[globals(), builtin],"base_id",True)
                    hexid = hex(VFSL([locals()]+SL+[globals(), builtin],"id",True))
                write(u''' <tr>
    <td>''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"tlmname",True) # u'$tlmname' on line 48, col 9
                if _v is not None: write(_filter(_v, rawExpr=u'$tlmname')) # from line 48, col 9.
                write(u'''</td>
    <td>''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"id",True) # u'$id' on line 49, col 9
                if _v is not None: write(_filter(_v, rawExpr=u'$id')) # from line 49, col 9.
                write(u''' (''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"hexid",True) # u'$hexid' on line 49, col 14
                if _v is not None: write(_filter(_v, rawExpr=u'$hexid')) # from line 49, col 14.
                write(u''')</td>
    <td>''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"type",True) # u'$type' on line 50, col 9
                if _v is not None: write(_filter(_v, rawExpr=u'$type')) # from line 50, col 9.
                write(u'''</td>
    <td>''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"comment",True) # u'$comment' on line 51, col 9
                if _v is not None: write(_filter(_v, rawExpr=u'$comment')) # from line 51, col 9.
                write(u'''</td>
 </tr>
''')
            write(u'''</table>
''')
        write(u'''</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_HtmlChannelTablePage= 'respond'

## END CLASS DEFINITION

if not hasattr(HtmlChannelTablePage, '_initCheetahAttributes'):
    templateAPIClass = getattr(HtmlChannelTablePage, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(HtmlChannelTablePage)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=HtmlChannelTablePage()).run()


