#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1554930768.404584
__CHEETAH_genTimestamp__ = 'Wed Apr 10 14:12:48 2019'
__CHEETAH_src__ = 'ChannelBody.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Apr 10 11:25:47 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class ChannelBody(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(ChannelBody, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Each file represents the information for a single event
# These module variables are used to instance the channel object within the Gse

''')
        if VFSL([locals()]+SL+[globals(), builtin],"ser_import",True) != None: # generated from line 4, col 1
            write(u'''import ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"ser_import",True) # u'$ser_import' on line 5, col 8
            if _v is not None: write(_filter(_v, rawExpr=u'$ser_import')) # from line 5, col 8.
            write(u'''
''')
        write(u'''
COMPONENT = "''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"component",True) # u'${component}' on line 8, col 14
        if _v is not None: write(_filter(_v, rawExpr=u'${component}')) # from line 8, col 14.
        write(u'''"

NAME = "''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 10, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 10, col 9.
        write(u'''"
ID  = ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"id",True) # u'${id}' on line 11, col 7
        if _v is not None: write(_filter(_v, rawExpr=u'${id}')) # from line 11, col 7.
        write(u'''
CHANNEL_DESCRIPTION = "''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"description",True) # u'${description}' on line 12, col 24
        if _v is not None: write(_filter(_v, rawExpr=u'${description}')) # from line 12, col 24.
        write(u'''"
TYPE = ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"type",True) # u'${type}' on line 13, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'${type}')) # from line 13, col 8.
        write(u'''
''')
        if VFSL([locals()]+SL+[globals(), builtin],"format_string",True) == None: # generated from line 14, col 1
            write(u'''FORMAT_STRING = None
''')
        else: # generated from line 16, col 1
            write(u'''FORMAT_STRING = "''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"format_string",True) # u'${format_string}' on line 17, col 18
            if _v is not None: write(_filter(_v, rawExpr=u'${format_string}')) # from line 17, col 18.
            write(u'''"
''')
        write(u'''
''')
        if VFSL([locals()]+SL+[globals(), builtin],"low_red",True) == None: # generated from line 20, col 1
            write(u'''LOW_RED = None
''')
        else: # generated from line 22, col 1
            write(u'''LOW_RED = ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"low_red",True) # u'$low_red' on line 23, col 11
            if _v is not None: write(_filter(_v, rawExpr=u'$low_red')) # from line 23, col 11.
            write(u'''
''')
        if VFSL([locals()]+SL+[globals(), builtin],"low_orange",True) == None: # generated from line 25, col 1
            write(u'''LOW_ORANGE = None
''')
        else: # generated from line 27, col 1
            write(u'''LOW_ORANGE = ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"low_orange",True) # u'$low_orange' on line 28, col 14
            if _v is not None: write(_filter(_v, rawExpr=u'$low_orange')) # from line 28, col 14.
            write(u'''
''')
        if VFSL([locals()]+SL+[globals(), builtin],"low_yellow",True) == None: # generated from line 30, col 1
            write(u'''LOW_YELLOW = None
''')
        else: # generated from line 32, col 1
            write(u'''LOW_YELLOW = ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"low_yellow",True) # u'$low_yellow' on line 33, col 14
            if _v is not None: write(_filter(_v, rawExpr=u'$low_yellow')) # from line 33, col 14.
            write(u'''
''')
        if VFSL([locals()]+SL+[globals(), builtin],"high_yellow",True) == None: # generated from line 35, col 1
            write(u'''HIGH_YELLOW = None
''')
        else: # generated from line 37, col 1
            write(u'''HIGH_YELLOW = ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"high_yellow",True) # u'$high_yellow' on line 38, col 15
            if _v is not None: write(_filter(_v, rawExpr=u'$high_yellow')) # from line 38, col 15.
            write(u'''
''')
        if VFSL([locals()]+SL+[globals(), builtin],"high_orange",True) == None: # generated from line 40, col 1
            write(u'''HIGH_ORANGE = None
''')
        else: # generated from line 42, col 1
            write(u'''HIGH_ORANGE = ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"high_orange",True) # u'$high_orange' on line 43, col 15
            if _v is not None: write(_filter(_v, rawExpr=u'$high_orange')) # from line 43, col 15.
            write(u'''
''')
        if VFSL([locals()]+SL+[globals(), builtin],"high_red",True) == None: # generated from line 45, col 1
            write(u'''HIGH_RED = None
''')
        else: # generated from line 47, col 1
            write(u'''HIGH_RED = ''')
            _v = VFSL([locals()]+SL+[globals(), builtin],"high_red",True) # u'$high_red' on line 48, col 12
            if _v is not None: write(_filter(_v, rawExpr=u'$high_red')) # from line 48, col 12.
            write(u'''
''')
        write(u'''
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_ChannelBody= 'respond'

## END CLASS DEFINITION

if not hasattr(ChannelBody, '_initCheetahAttributes'):
    templateAPIClass = getattr(ChannelBody, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(ChannelBody)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=ChannelBody()).run()


