#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1554930756.31931
__CHEETAH_genTimestamp__ = 'Wed Apr 10 14:12:36 2019'
__CHEETAH_src__ = 'publicPortCpp.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Apr 10 11:25:47 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class publicPortCpp(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(publicPortCpp, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''    Input''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 1, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 1, col 10.
        write(u'''Port::Input''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 1, col 28
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 1, col 28.
        write(u'''Port(void) : 
        Fw::InputPortBase(), 
        m_func(0) {
    }
    
    void Input''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 6, col 15
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 6, col 15.
        write(u'''Port::init(void) {
        Fw::InputPortBase::init();
    }

    void Input''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 10, col 15
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 10, col 15.
        write(u'''Port::addCallComp(Fw::PassiveComponentBase* callComp, CompFuncPtr funcPtr) {
        FW_ASSERT(callComp);
        FW_ASSERT(funcPtr);

        this->m_comp = callComp;
        this->m_func = funcPtr;
        this->m_connObj = callComp;
    }

    // call virtual logging function for component
    ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"return_type",True) # u'${return_type}' on line 20, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'${return_type}')) # from line 20, col 5.
        write(u'''Input''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 20, col 24
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 20, col 24.
        write(u'''Port::invoke(''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"args_proto_string",True) # u'${args_proto_string}' on line 20, col 44
        if _v is not None: write(_filter(_v, rawExpr=u'${args_proto_string}')) # from line 20, col 44.
        write(u''') {

#if FW_PORT_TRACING == 1        
        this->trace();
#endif
        FW_ASSERT(this->m_comp);
        FW_ASSERT(this->m_func);
''')
        if VFSL([locals()]+SL+[globals(), builtin],"return_type",True)[:4] == "void": # generated from line 27, col 1
            if VFSL([locals()]+SL+[globals(), builtin],"args_string",True) == "": # generated from line 28, col 1
                write(u'''        this->m_func(this->m_comp, this->m_portNum);
''')
            else: # generated from line 30, col 1
                write(u'''        this->m_func(this->m_comp, this->m_portNum, ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"args_string",True) # u'${args_string}' on line 31, col 53
                if _v is not None: write(_filter(_v, rawExpr=u'${args_string}')) # from line 31, col 53.
                write(u''');
''')
        else: # generated from line 33, col 1
            if VFSL([locals()]+SL+[globals(), builtin],"args_string",True) == "": # generated from line 34, col 1
                write(u'''        return this->m_func(this->m_comp, this->m_portNum);
''')
            else: # generated from line 36, col 1
                write(u'''        return this->m_func(this->m_comp, this->m_portNum, ''')
                _v = VFSL([locals()]+SL+[globals(), builtin],"args_string",True) # u'${args_string}' on line 37, col 60
                if _v is not None: write(_filter(_v, rawExpr=u'${args_string}')) # from line 37, col 60.
                write(u''');
''')
        write(u'''    }

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_publicPortCpp= 'respond'

## END CLASS DEFINITION

if not hasattr(publicPortCpp, '_initCheetahAttributes'):
    templateAPIClass = getattr(publicPortCpp, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(publicPortCpp)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=publicPortCpp()).run()


